services:
  proalgotrader_core:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: proalgotrader_core
    command: ["python", "main.py", "--environment", "development"]
    volumes:
      - ./project:/app/project
    networks:
      - proalgotrader_core_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "proalgotrader.test:host-gateway"
      - "proalgotrader_laravel.test:host-gateway"
networks:
  proalgotrader_core_network:
    driver: bridge
