services:
  proalgotrader_core:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-proalgotrader_core}
    container_name: ${CONTAINER_NAME:-proalgotrader_core}
    command: [
      "uv",
      "run",
      "run.py",
      "--mode", "${MODE:-paper}",
      "--environment", "${ENVIRONMENT:-development}",
      "--api_url", "${API_URL:-https://proalgotrader.com}"
    ]
    volumes:
      - ./project:/app/project
      - ./run.py:/app/run.py
      - ./.env.paper:/app/.env.paper
      - ./.env.live:/app/.env.live
    environment:
      - CONTAINER_NAME=${CONTAINER_NAME:-proalgotrader_core}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - API_URL=${API_URL:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "proalgotrader.com:host-gateway"
